name: Manual workflow Maven Package

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Echo workspace
      run: echo "github.workspace = ${{ github.workspace }}"
    - name: Echo env workspace
      run: echo "$GITHUB_WORKSPACE"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Show settings.xml
      run: cat $GITHUB_WORKSPACE/settings.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
