name: Page generation from templates

on:
  # Trigger on page_build, as well as release, fork, push, watch and issues events
  page_build:
  release:
  fork:
  push:
  watch:
  issues:
    types:
      - opened
      - closed
      - edited
      - deleted
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
    - uses: itamarc/action-itemplate-ghpages@v1test
      with:
        templates_folder: ':bluish:'
        pages_branch: 'gh-pages'
        pages_folder: 'docs'
        timezone: 'America/Sao_Paulo'
        publish_readme_md: 'true'
        syntax_highlight_enable: 'true'
        syntax_highlight_theme: 'coy'
        log_level: 'INFO'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
